version: "3"

services:
  api:
    container_name: magic-scanner-api
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/go/src/app
    environment:
      - NOTION_TOKEN=secret_rsMBrVPxnAu5y5hPE31F1cMAW4DPWeHOH2xFlQEq052
      - VISION_TOKEN=AIzaSyDI6Es5w6Kdv_0C7iFklhzuE3NNFrYi0Aw
